# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
os:
  - windows
  - linux
  - osx

jobs:
  include:
   - dist: focal

env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"

branches:
  only:
    - master
    - stable
    - main

git:
  - sparse_checkout: skip-worktree-map-file
  - autocrlf: input
  - symlinks: true  
  - depth: true
  - clonr: true

before_script:
  - composer install -no-interaction
  
script:
  - /usr/lib/R
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
  
